language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew
 - chmod +x jars.sh
script:
 - ./gradlew assemble && ./jars.sh -e -s -c -g FetchQuest -g EvilThing -g OpenDoor -g OpenDoor2 -g TreasureQuest -g Hanoi -g WSC && ./gradlew check
after_failure:
 - cat build/reports/*/*.xml
cache:
 directories:
  - $HOME/.m2
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches
notifications:
  slack: tecnicas7510-01-2016:W5XvT1AblqTWeZaNNblKXWfh
