language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew
 - chmod +x jars.sh
 - chmod +x all.sh
script:
 - ./all.sh && ./gradlew check
after_failure:
 - cat build/reports/*/*.xml
cache:
 directories:
  - $HOME/.m2
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches
notifications:
  slack: tecnicas7510-01-2016:W5XvT1AblqTWeZaNNblKXWfh
